steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'DATASET_NAME=myherodotus'
  script: |
    docker build -t us-west1-docker.pkg.dev/$PROJECT_ID/my-herodotus/evaluations:v0.1.0 .
  automapSubstitutions: true
images:
- 'us-west1-docker.pkg.dev/$PROJECT_ID/my-herodotus/evaluations:v0.1.0'